//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroundWellDesign.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorInfo() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GroundWellDesign.Properties.ErrorInfo", typeof(ErrorInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 岩层基本参数出错：第一层不为地表。 的本地化字符串。
        /// </summary>
        internal static string BaseParamsError1 {
            get {
                return ResourceManager.GetString("BaseParamsError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 岩层基本参数出错：没有录入煤层。 的本地化字符串。
        /// </summary>
        internal static string BaseParamsError2 {
            get {
                return ResourceManager.GetString("BaseParamsError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 岩层基本参数出错：煤层没有底板。 的本地化字符串。
        /// </summary>
        internal static string BaseParamsError3 {
            get {
                return ResourceManager.GetString("BaseParamsError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 岩层基本参数出错：没有录入任何岩层。 的本地化字符串。
        /// </summary>
        internal static string BaseParamsError4 {
            get {
                return ResourceManager.GetString("BaseParamsError4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计算寻找关键层出错，请检查数据合理性。 的本地化字符串。
        /// </summary>
        internal static string ComputeKeyLayerError {
            get {
                return ResourceManager.GetString("ComputeKeyLayerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关键层相关计算出错，请检查数据合理性。 的本地化字符串。
        /// </summary>
        internal static string ComputeKeyLayerOffsetError {
            get {
                return ResourceManager.GetString("ComputeKeyLayerOffsetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安全系数计算出错，请检查数据合理性。 的本地化字符串。
        /// </summary>
        internal static string ComputeSafeError {
            get {
                return ResourceManager.GetString("ComputeSafeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水泥环增益计算出错，请检查数据合理性。 的本地化字符串。
        /// </summary>
        internal static string ComputeZengYiError {
            get {
                return ResourceManager.GetString("ComputeZengYiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有填写工作面推进速度。 的本地化字符串。
        /// </summary>
        internal static string NoGzmsd {
            get {
                return ResourceManager.GetString("NoGzmsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有填写回采区走向长度或倾向长度 的本地化字符串。
        /// </summary>
        internal static string NoHcqcdError {
            get {
                return ResourceManager.GetString("NoHcqcdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未计算关键层或没有关键层。 的本地化字符串。
        /// </summary>
        internal static string NoKeyParamsError {
            get {
                return ResourceManager.GetString("NoKeyParamsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有填写煤层厚度。 的本地化字符串。
        /// </summary>
        internal static string NoMchdError {
            get {
                return ResourceManager.GetString("NoMchdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有填写评价系数修正系数。 的本地化字符串。
        /// </summary>
        internal static string NoPjxsxzError {
            get {
                return ResourceManager.GetString("NoPjxsxzError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 套管弹性模量格式不正确，请重新输入。 的本地化字符串。
        /// </summary>
        internal static string TxmlSyntaxError {
            get {
                return ResourceManager.GetString("TxmlSyntaxError", resourceCulture);
            }
        }
    }
}
