//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroundWellDesign.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GroundWellDesign.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 CAD初始化失败，请检查是否注册组件。 的本地化字符串。
        /// </summary>
        internal static string CADNotRegisteredError {
            get {
                return ResourceManager.GetString("CADNotRegisteredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建表异常。 的本地化字符串。
        /// </summary>
        internal static string CreateTableError {
            get {
                return ResourceManager.GetString("CreateTableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 C:\\ProgramData\\GroundWellDesign\\ 的本地化字符串。
        /// </summary>
        internal static string DataBaseDirectory {
            get {
                return ResourceManager.GetString("DataBaseDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yanceng.db 的本地化字符串。
        /// </summary>
        internal static string DataBaseName {
            get {
                return ResourceManager.GetString("DataBaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序列化文件到对象异常。 的本地化字符串。
        /// </summary>
        internal static string DeserializeError {
            get {
                return ResourceManager.GetString("DeserializeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dump到对象为空。 的本地化字符串。
        /// </summary>
        internal static string DumpEmpty {
            get {
                return ResourceManager.GetString("DumpEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dump到对象异常。 的本地化字符串。
        /// </summary>
        internal static string DumpError {
            get {
                return ResourceManager.GetString("DumpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将DataGrid保存到Excel文件出现异常。 的本地化字符串。
        /// </summary>
        internal static string ExportExcelError {
            get {
                return ResourceManager.GetString("ExportExcelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建数据库表失败。 的本地化字符串。
        /// </summary>
        internal static string InitDataBaseTablesError {
            get {
                return ResourceManager.GetString("InitDataBaseTablesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化运行时公式库失败。 的本地化字符串。
        /// </summary>
        internal static string InitLogicError {
            get {
                return ResourceManager.GetString("InitLogicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入字段异常。 的本地化字符串。
        /// </summary>
        internal static string InsertColumeError {
            get {
                return ResourceManager.GetString("InsertColumeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该岩层记录已存在，是否更新数据库记录？选择\&quot;否\&quot;新增一条。 的本地化字符串。
        /// </summary>
        internal static string LayerExistPrompt {
            get {
                return ResourceManager.GetString("LayerExistPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License.lic 的本地化字符串。
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取Excel失败。 的本地化字符串。
        /// </summary>
        internal static string LoadExcelError {
            get {
                return ResourceManager.GetString("LoadExcelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开数据库出现异常。 的本地化字符串。
        /// </summary>
        internal static string OpenDataBaseError {
            get {
                return ResourceManager.GetString("OpenDataBaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败。 的本地化字符串。
        /// </summary>
        internal static string OperateNotOk {
            get {
                return ResourceManager.GetString("OperateNotOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功。 的本地化字符串。
        /// </summary>
        internal static string OperateOk {
            get {
                return ResourceManager.GetString("OperateOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询所有岩层时异常。 的本地化字符串。
        /// </summary>
        internal static string QueryDBLayersError {
            get {
                return ResourceManager.GetString("QueryDBLayersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询所有岩层信息不全。 的本地化字符串。
        /// </summary>
        internal static string QueryDBLayersInfoError {
            get {
                return ResourceManager.GetString("QueryDBLayersInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询字段是否存在时出现异常。 的本地化字符串。
        /// </summary>
        internal static string QueryExistColumeError {
            get {
                return ResourceManager.GetString("QueryExistColumeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询表是否存在时出现异常。 的本地化字符串。
        /// </summary>
        internal static string QueryExistTableError {
            get {
                return ResourceManager.GetString("QueryExistTableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询所有地面井名字出错。 的本地化字符串。
        /// </summary>
        internal static string QueryWellNamesError {
            get {
                return ResourceManager.GetString("QueryWellNamesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存到数据库出现异常。 的本地化字符串。
        /// </summary>
        internal static string SaveToDBError {
            get {
                return ResourceManager.GetString("SaveToDBError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存到数据库岩层信息不全。 的本地化字符串。
        /// </summary>
        internal static string SaveToDBInfoError {
            get {
                return ResourceManager.GetString("SaveToDBInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请至少选择一个岩层。 的本地化字符串。
        /// </summary>
        internal static string SelectAtLeastOnePrompt {
            get {
                return ResourceManager.GetString("SelectAtLeastOnePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序列化对象到文件异常。 的本地化字符串。
        /// </summary>
        internal static string SerializeError {
            get {
                return ResourceManager.GetString("SerializeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 竖三带计算出错，请检查数据合理性。 的本地化字符串。
        /// </summary>
        internal static string ShuSanDaiError {
            get {
                return ResourceManager.GetString("ShuSanDaiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入矿井名称。 的本地化字符串。
        /// </summary>
        internal static string TypeWellNamePrompt {
            get {
                return ResourceManager.GetString("TypeWellNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入文件失败。 的本地化字符串。
        /// </summary>
        internal static string WriteFileError {
            get {
                return ResourceManager.GetString("WriteFileError", resourceCulture);
            }
        }
    }
}
